sudo: required

language: 
  - python
  - cpp

python: 
  - "3.4"

script:
  - ./unitframe.py -ut
  - ./gate.py -ut
  - ./gate.py

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ --version

notifications:
  email: true
